version: '3'

services:
  iplayerapi:
    image: bgoldhawk/iplayer_api:latest
    user: root
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8080:80"